#!/usr/bin/env bash

set -e
source $(dirname $(realpath $0))/../CUSTOM_INFO

# a docker image tag with the format 'name:tag'.
# generated by CUSTOM_INFO above.
# eg: alexlee/test-u:latest
IMGTAG=${USERNAME:-$(id -un)}/${IMGNAME:-"test-u"}:${VERSION:-"latest"}

install_prefix=$HOME/.local
[[ ! -d $1 ]] || install_prefix=$(realpath $1)

install_path=${install_prefix}/docker_env

[[ -d $install_path ]] || mkdir -p $install_path

FUNC_NAME=${FUNC_ALIAS:-${ENTRY:-bash}}

install_name=${FUNC_NAME##*/}_${IMGNAME:-"test-u"}_env

install_path=${install_path}/${install_name}

cat <<EOF > ${install_path}
docker_${FUNC_NAME##*/}() {
    docker run \\
        -it \\
        --rm \\
        -u $(id -u) \\
        --entrypoint \${ENTRY:-"${ENTRY}"} \\
        -v /home/\${USERNAME}:/home/\${USERNAME} \\
        -v /media:/media \\
        --hostname ${IMGNAME:-"test-u"} \\
        -w \$(realpath \$(pwd)) \\
        ${IMGTAG} \\
        \$@
    }

PASS=$RANDOM
if [[ "\${BASH_ARGV0##*/}" != "${install_name}" ]]; then
    bash \${BASH_ARGV} \${PASS};
elif [[ "\${BASH_ARGV}" == "\${PASS}" ]]; then
    echo -e "\033[1;3;32m""command available:""\033[0;34m"
    typeset -f | awk '/ \(\) \$/ {print " \033[1;32m"\$1"\033[0;34m"}'
else
    echo -e "\033[1;3;32m""USAGE:""\033[0;34m"
    echo -e "\$ \033[1;32m""source \${BASH_ARGV0}""\033[0;34m"
fi
EOF

echo -e "First, exec: \n\
    source $install_path"
echo -e "Then, use: \n\
    [ENTRY=<entry>] docker_${FUNC_NAME##*/} [arg1]..."
